package DAL;
// Generated 22-dec-2014 14:06:09 by Hibernate Tools 4.3.1

/**
 * Landstreek generated by hbm2java
 */
public class Landstreek implements java.io.Serializable {

    private Integer landstreekId;
    private Land tblLand;
    private String naam;
    private String omschrijving;
    private String link;
    private String foto;

    public Landstreek() {
    }

    public Landstreek(Land tblLand, String naam, String omschrijving, String link, String foto) {
        this.tblLand = tblLand;
        this.naam = naam;
        this.omschrijving = omschrijving;
        this.link = link;
        this.foto = "Banner04.jpg";
//       this.foto = foto;
    }

    public Integer getLandstreekId() {
        return this.landstreekId;
    }

    public void setLandstreekId(Integer landstreekId) {
        this.landstreekId = landstreekId;
    }

    public Land getTblLand() {
        return this.tblLand;
    }

    public String getLand() {
        return this.tblLand.getNaam();
    }

    public void setTblLand(Land tblLand) {
        this.tblLand = tblLand;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public String getOmschrijving() {
        return this.omschrijving;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getFoto() {
        this.foto = "Banner04.jpg";
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

}
