package DAL;
// Generated 22-dec-2014 14:06:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Land generated by hbm2java
 */
public class Land  implements java.io.Serializable {


     private Integer landId;
     private String naam;
     private String omschrijving;
     private String link;
     private String foto;
     private Set tblLandstreeks = new HashSet(0);

    public Land() {
    }

	
    public Land(String naam, String omschrijving, String link, String foto) {
        this.naam = naam;
        this.omschrijving = omschrijving;
        this.link = link;
        this.foto = foto;
    }
    public Land(String naam, String omschrijving, String link, String foto, Set tblLandstreeks) {
       this.naam = naam;
       this.omschrijving = omschrijving;
       this.link = link;
       this.foto = foto;
       this.tblLandstreeks = tblLandstreeks;
    }
   
    public Integer getLandId() {
        return this.landId;
    }
    
    public void setLandId(Integer landId) {
        this.landId = landId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getTblLandstreeks() {
        return this.tblLandstreeks;
    }
    
    public void setTblLandstreeks(Set tblLandstreeks) {
        this.tblLandstreeks = tblLandstreeks;
    }




}


