package DAL;
// Generated 22-dec-2014 18:32:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Wijn generated by hbm2java
 */
public class Wijn implements java.io.Serializable {


     private Integer id;
     private String name;
     private int typeid;
     private String platter;
     private int year;
     private BigDecimal packprice;
     private byte packsize;
     private BigDecimal price;
     private BigDecimal volume;
     private String description;
     private int estateid;
     private int imageid;
     private byte flags;

    public Wijn() {
    }

    public Wijn(String name, int typeid, String platter, int year, BigDecimal packprice, byte packsize, BigDecimal price, BigDecimal volume, String description, int estateid, int imageid, byte flags) {
       this.name = name;
       this.typeid = typeid;
       this.platter = platter;
       this.year = year;
       this.packprice = packprice;
       this.packsize = packsize;
       this.price = price;
       this.volume = volume;
       this.description = description;
       this.estateid = estateid;
       this.imageid = imageid;
       this.flags = flags;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getTypeid() {
        return this.typeid;
    }
    
    public void setTypeid(int typeid) {
        this.typeid = typeid;
    }
    public String getPlatter() {
        return this.platter;
    }
    
    public void setPlatter(String platter) {
        this.platter = platter;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    public BigDecimal getPackprice() {
        return this.packprice;
    }
    
    public void setPackprice(BigDecimal packprice) {
        this.packprice = packprice;
    }
    public byte getPacksize() {
        return this.packsize;
    }
    
    public void setPacksize(byte packsize) {
        this.packsize = packsize;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getVolume() {
        return this.volume;
    }
    
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getEstateid() {
        return this.estateid;
    }
    
    public void setEstateid(int estateid) {
        this.estateid = estateid;
    }
    public int getImageid() {
        return this.imageid;
    }
    
    public void setImageid(int imageid) {
        this.imageid = imageid;
    }
    public byte getFlags() {
        return this.flags;
    }
    
    public void setFlags(byte flags) {
        this.flags = flags;
    }

 public String getFoto() {
        return "AlleeBleueIsabeau.jpg";
    }


}


